/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareSlugRouteImport } from './routes/share.$slug'
import { Route as AuthenticatedMyDesignsRouteImport } from './routes/_authenticated/my-designs'
import { Route as ApiPublicRenderRoomRouteImport } from './routes/api/public/render-room'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareSlugRoute = ShareSlugRouteImport.update({
  id: '/share/$slug',
  path: '/share/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMyDesignsRoute = AuthenticatedMyDesignsRouteImport.update({
  id: '/my-designs',
  path: '/my-designs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicRenderRoomRoute = ApiPublicRenderRoomRouteImport.update({
  id: '/api/public/render-room',
  path: '/api/public/render-room',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/my-designs': typeof AuthenticatedMyDesignsRoute
  '/share/$slug': typeof ShareSlugRoute
  '/api/public/render-room': typeof ApiPublicRenderRoomRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/my-designs': typeof AuthenticatedMyDesignsRoute
  '/share/$slug': typeof ShareSlugRoute
  '/api/public/render-room': typeof ApiPublicRenderRoomRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/my-designs': typeof AuthenticatedMyDesignsRoute
  '/share/$slug': typeof ShareSlugRoute
  '/api/public/render-room': typeof ApiPublicRenderRoomRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/my-designs'
    | '/share/$slug'
    | '/api/public/render-room'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/my-designs' | '/share/$slug' | '/api/public/render-room'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/my-designs'
    | '/share/$slug'
    | '/api/public/render-room'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ShareSlugRoute: typeof ShareSlugRoute
  ApiPublicRenderRoomRoute: typeof ApiPublicRenderRoomRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$slug': {
      id: '/share/$slug'
      path: '/share/$slug'
      fullPath: '/share/$slug'
      preLoaderRoute: typeof ShareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my-designs': {
      id: '/_authenticated/my-designs'
      path: '/my-designs'
      fullPath: '/my-designs'
      preLoaderRoute: typeof AuthenticatedMyDesignsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/render-room': {
      id: '/api/public/render-room'
      path: '/api/public/render-room'
      fullPath: '/api/public/render-room'
      preLoaderRoute: typeof ApiPublicRenderRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMyDesignsRoute: typeof AuthenticatedMyDesignsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMyDesignsRoute: AuthenticatedMyDesignsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ShareSlugRoute: ShareSlugRoute,
  ApiPublicRenderRoomRoute: ApiPublicRenderRoomRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
